# Generated by Django 6.0.1 on 2026-02-02 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0003_alter_question_category_alter_question_creator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_questions", models.IntegerField(default=0)),
                ("total_answers", models.IntegerField(default=0)),
                ("average_score", models.FloatField(default=0.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="questions.category",
                    ),
                ),
                (
                    "easiest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="easiest_in_category",
                        to="questions.question",
                    ),
                ),
                (
                    "most_difficult",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="most_difficult_in_category",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["category"], name="analytics_c_categor_dff73d_idx"
                    ),
                    models.Index(
                        fields=["-average_score"], name="analytics_c_average_dad193_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("questions_answered", models.IntegerField(default=0)),
                ("questions_viewed", models.IntegerField(default=0)),
                ("average_score", models.FloatField(default=0.0)),
                ("time_spent", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="analytics_d_date_db3351_idx"),
                    models.Index(
                        fields=["user"], name="analytics_d_user_id_73d74d_idx"
                    ),
                    models.Index(fields=["-date"], name="analytics_d_date_ebc965_idx"),
                ],
                "unique_together": {("date", "user")},
            },
        ),
        migrations.CreateModel(
            name="PerformanceTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("score_trend", models.FloatField(default=0.0)),
                ("accuracy_trend", models.FloatField(default=0.0)),
                ("speed_trend", models.FloatField(default=0.0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_trends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="analytics_p_user_id_55161e_idx"
                    ),
                    models.Index(fields=["date"], name="analytics_p_date_f7dc22_idx"),
                ],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_questions_answered", models.IntegerField(default=0)),
                ("total_questions_viewed", models.IntegerField(default=0)),
                ("average_score", models.FloatField(default=0.0)),
                ("highest_score", models.FloatField(default=0.0)),
                ("lowest_score", models.FloatField(default=0.0)),
                ("total_time_spent", models.IntegerField(default=0)),
                ("average_time_per_question", models.FloatField(default=0.0)),
                ("favorite_count", models.IntegerField(default=0)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="analytics_u_user_id_5ac7bf_idx"
                    ),
                    models.Index(
                        fields=["-average_score"], name="analytics_u_average_61347a_idx"
                    ),
                    models.Index(
                        fields=["-total_questions_answered"],
                        name="analytics_u_total_q_586afc_idx",
                    ),
                ],
            },
        ),
    ]
