# Generated by Django 5.2.8 on 2026-01-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="difficult",
            new_name="difficulty",
        ),
    ]
