# Generated by Django 6.0.1 on 2026-02-02 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0003_alter_question_category_alter_question_creator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preferred_categories", models.JSONField(default=dict)),
                ("preferred_difficulty", models.JSONField(default=dict)),
                ("weak_areas", models.JSONField(default=list)),
                ("strong_areas", models.JSONField(default=list)),
                ("avg_score", models.FloatField(default=0.0)),
                ("total_answered", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.FloatField(default=0.0)),
                ("common_users", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "question_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_as_a",
                        to="questions.question",
                    ),
                ),
                (
                    "question_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_as_b",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["question_a"], name="recommender_questio_96d13a_idx"
                    ),
                    models.Index(
                        fields=["question_b"], name="recommender_questio_6fd201_idx"
                    ),
                    models.Index(
                        fields=["similarity_score"],
                        name="recommender_similar_357974_idx",
                    ),
                ],
                "unique_together": {("question_a", "question_b")},
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("user_based", "基于用户的协同过滤"),
                            ("item_based", "基于物品的协同过滤"),
                            ("hybrid", "混合推荐"),
                            ("content_based", "基于内容的推荐"),
                        ],
                        default="hybrid",
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("reason", models.TextField(blank=True)),
                ("is_viewed", models.BooleanField(default=False)),
                ("is_answered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="questions.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="recommender_user_id_e7c2d7_idx"
                    ),
                    models.Index(
                        fields=["question"], name="recommender_questio_9a1b0e_idx"
                    ),
                    models.Index(fields=["score"], name="recommender_score_e9aeed_idx"),
                    models.Index(
                        fields=["-created_at"], name="recommender_created_871ca9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.FloatField(default=0.0)),
                ("common_questions", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_as_a",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similarity_as_b",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_a"], name="recommender_user_a__462bae_idx"
                    ),
                    models.Index(
                        fields=["user_b"], name="recommender_user_b__8c8b37_idx"
                    ),
                    models.Index(
                        fields=["similarity_score"],
                        name="recommender_similar_c8bb98_idx",
                    ),
                ],
                "unique_together": {("user_a", "user_b")},
            },
        ),
    ]
