# Generated by Django 6.0.1 on 2026-02-02 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("practice", "0005_remove_interaction_practice_in_user_id_a83a25_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoringHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scoring_method",
                    models.CharField(
                        choices=[
                            ("embedding", "基于嵌入的评分"),
                            ("llm", "基于大语言模型的评分"),
                            ("manual", "人工评分"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_history",
                        to="practice.interaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["interaction"], name="scoring_sco_interac_3470d8_idx"
                    ),
                    models.Index(
                        fields=["scoring_method"], name="scoring_sco_scoring_38be4a_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="scoring_sco_created_404b18_idx"
                    ),
                ],
            },
        ),
    ]
