# Generated by Django 5.2.8 on 2026-01-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interaction",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
