# Generated by Django 5.2.8 on 2026-01-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0002_interaction_is_submitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="interaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("viewed", "仅浏览"),
                    ("draft", "草稿"),
                    ("submitted", "已提交"),
                    ("scored", "已评分"),
                ],
                default="viewed",
                max_length=20,
            ),
        ),
    ]
