# Generated by Django 5.2.8 on 2026-01-31 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0003_interaction_status"),
        ("questions", "0003_alter_question_category_alter_question_creator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="interaction",
        ),
        migrations.RemoveField(
            model_name="history",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="interaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="interaction",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="interaction",
            index=models.Index(
                fields=["user", "question"], name="practice_in_user_id_a83a25_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="interaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_submitted", False)),
                fields=("user", "question", "is_submitted"),
                name="unique_draft_per_user_question",
            ),
        ),
        migrations.DeleteModel(
            name="History",
        ),
    ]
