# Generated by Django 5.2.8 on 2026-01-31 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0004_remove_history_interaction_remove_history_user_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="interaction",
            name="practice_in_user_id_a83a25_idx",
        ),
        migrations.RemoveField(
            model_name="interaction",
            name="feedback",
        ),
    ]
