# Generated by Django 5.2.8 on 2026-02-17 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("questions", "0003_alter_question_category_alter_question_creator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("java", "Java"),
                            ("javascript", "JavaScript"),
                            ("cpp", "C++"),
                            ("go", "Go"),
                            ("rust", "Rust"),
                        ],
                        default="python",
                        max_length=20,
                    ),
                ),
                (
                    "template_code",
                    models.TextField(help_text="代码模板，用户在此基础上编写"),
                ),
                (
                    "starter_code",
                    models.TextField(
                        blank=True, help_text="初始代码，自动填充到编辑器"
                    ),
                ),
                (
                    "function_signature",
                    models.CharField(
                        help_text="函数签名，如 def solution(nums):", max_length=200
                    ),
                ),
                (
                    "time_limit",
                    models.IntegerField(default=1000, help_text="时间限制（毫秒）"),
                ),
                (
                    "memory_limit",
                    models.IntegerField(default=256, help_text="内存限制（MB）"),
                ),
                ("is_public", models.BooleanField(default=True, help_text="是否公开")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_question",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "代码题目",
                "verbose_name_plural": "代码题目",
                "db_table": "code_questions",
            },
        ),
        migrations.CreateModel(
            name="CodeNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="笔记内容")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "code_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="code_questions.codequestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "代码题目笔记",
                "verbose_name_plural": "代码题目笔记",
                "db_table": "code_notes",
            },
        ),
        migrations.CreateModel(
            name="CodeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(help_text="提交的代码")),
                ("language", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("accepted", "通过"),
                            ("wrong_answer", "答案错误"),
                            ("time_limit_exceeded", "超时"),
                            ("memory_limit_exceeded", "内存超限"),
                            ("runtime_error", "运行时错误"),
                            ("compile_error", "编译错误"),
                            ("system_error", "系统错误"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "runtime",
                    models.IntegerField(
                        blank=True, help_text="运行时间（毫秒）", null=True
                    ),
                ),
                (
                    "memory",
                    models.IntegerField(
                        blank=True, help_text="内存使用（KB）", null=True
                    ),
                ),
                (
                    "passed_test_cases",
                    models.IntegerField(default=0, help_text="通过的测试用例数"),
                ),
                (
                    "total_test_cases",
                    models.IntegerField(default=0, help_text="总测试用例数"),
                ),
                ("error_message", models.TextField(blank=True, help_text="错误信息")),
                (
                    "test_case_results",
                    models.JSONField(
                        blank=True, default=dict, help_text="测试用例结果详情"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "code_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="code_questions.codequestion",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "代码提交",
                "verbose_name_plural": "代码提交",
                "db_table": "code_submissions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField(help_text="输入数据，JSON 格式")),
                ("expected_output", models.TextField(help_text="期望输出，JSON 格式")),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, help_text="是否隐藏（隐藏用例不显示给用户）"
                    ),
                ),
                (
                    "is_sample",
                    models.BooleanField(default=False, help_text="是否为示例用例"),
                ),
                ("order", models.IntegerField(default=0, help_text="排序")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "code_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="code_questions.codequestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例",
                "verbose_name_plural": "测试用例",
                "db_table": "test_cases",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CodeBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "code_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="code_questions.codequestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "代码题目收藏",
                "verbose_name_plural": "代码题目收藏",
                "db_table": "code_bookmarks",
                "unique_together": {("user", "code_question")},
            },
        ),
    ]
